# Generated by Django 5.2.12 on 2026-04-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_options_alter_article_body'),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('campaign_type', models.CharField(choices=[('blog_post', 'Blog post announcement'), ('newsletter', 'Newsletter'), ('announcement', 'Announcement')], default='newsletter', max_length=20)),
                ('subject', models.CharField(max_length=180)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('heading', models.CharField(blank=True, max_length=220)),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text='Write in Markdown or paste HTML. Blog-post campaigns can leave this blank.')),
                ('call_to_action_label', models.CharField(blank=True, max_length=80)),
                ('call_to_action_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to='content.article')),
            ],
            options={
                'verbose_name': 'Email campaign',
                'verbose_name_plural': 'Email campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='engagement.newslettercampaign')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_deliveries', to='engagement.subscriber')),
            ],
            options={
                'verbose_name': 'Email delivery',
                'verbose_name_plural': 'Email deliveries',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscriber'), name='unique_newsletter_delivery')],
            },
        ),
    ]
