# Generated by Django 5.2.12 on 2026-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Article tag',
                'verbose_name_plural': 'Article tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('live_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('ai-education', 'AI Education'), ('e-commerce', 'E-commerce'), ('saas', 'SaaS'), ('corporate-website', 'Corporate Website'), ('nonprofit-platform', 'Nonprofit Platform')], max_length=40)),
                ('tech_stack', models.CharField(help_text='Comma-separated stack or role labels.', max_length=255)),
                ('role_label', models.CharField(blank=True, max_length=120)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField(help_text='Rich-text compatible HTML content.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('author_name', models.CharField(default='Vincent Dania', max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=6)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='content.articlecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.articletag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-featured', '-published_at', '-created_at'],
            },
        ),
    ]
