# Generated by Django 5.2.12 on 2026-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-featured', '-published_at', '-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Write in Markdown or paste HTML. The public site renders the formatted result.'),
        ),
    ]
