# Generated by Django 5.2.12 on 2026-03-28 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('issuer', models.CharField(max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CredibilityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Credibility stat',
                'verbose_name_plural': 'Credibility stats',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_in_progress', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education credential',
                'verbose_name_plural': 'Education credentials',
                'ordering': ['order', '-end_year', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('organization', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('achievements', models.TextField(help_text='Add one achievement per line.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpertiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('skills', models.TextField(help_text='Add one skill per line.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expertise category',
                'verbose_name_plural': 'Expertise categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='briefcase', max_length=40)),
                ('value', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Impact metric',
                'verbose_name_plural': 'Impact metrics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Programme Leadership. Technology Delivery. Thoughtful Systems Change.', max_length=120)),
                ('hero_title', models.CharField(default='Leading donor-funded programmes and building digital systems that deliver measurable social impact.', max_length=255)),
                ('hero_subtitle', models.TextField(default='Vincent Dania is a senior programme and project leader, IT professional, and product-minded builder working across governance, gender justice, social protection, and digital transformation.')),
                ('about_title', models.CharField(default='A hybrid professional built for complex delivery.', max_length=160)),
                ('about_body', models.TextField(default='With more than 14 years of experience, Vincent Dania brings together programme leadership, donor accountability, monitoring and learning, and systems thinking.\n\nHis work spans donor-funded implementation, institutional strengthening, gender justice, social protection, and technology-enabled delivery. He is equally comfortable coordinating multi-stakeholder programmes, translating policy into implementation, or working directly with builders to deliver digital products that improve accountability and learning.')),
                ('builder_title', models.CharField(default='He does not just manage projects. He builds systems.', max_length=160)),
                ('builder_intro', models.TextField(default='Alongside programme leadership, Vincent has built and shipped public-facing digital products spanning AI education, SaaS, e-commerce, corporate web platforms, and nonprofit digital presence.')),
                ('expertise_title', models.CharField(default='Core competencies shaped by delivery, policy, and execution.', max_length=160)),
                ('expertise_intro', models.TextField(default="The strongest thread across Vincent's work is execution: designing clear systems, aligning stakeholders, and delivering outcomes that hold under scrutiny.")),
                ('education_title', models.CharField(default='Credentials that reinforce technical depth and management discipline.', max_length=160)),
                ('education_intro', models.TextField(default='His academic and professional training strengthens a practice grounded in programme discipline, digital fluency, and continuous learning.')),
                ('thought_leadership_title', models.CharField(default='Writing on technology, policy, and practical delivery.', max_length=160)),
                ('thought_leadership_intro', models.TextField(default='Recent essays and research explore how technology, governance, and public systems can be designed for credibility, inclusion, and long-term value.')),
                ('opportunities_title', models.CharField(default='Open to opportunities that require judgment, delivery discipline, and systems thinking.', max_length=160)),
                ('opportunities_copy', models.TextField(default='Vincent is open to senior programme leadership, project management, consulting, advisory, remote, and onsite opportunities where strategy must translate into execution.')),
                ('contact_title', models.CharField(default='Initiate a conversation.', max_length=160)),
                ('contact_copy', models.TextField(default='If you are hiring, building a programme, or need a technology-enabled delivery partner, Vincent welcomes a thoughtful conversation.')),
            ],
            options={
                'verbose_name': 'Profile content',
                'verbose_name_plural': 'Profile content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vincent Dania', max_length=120)),
                ('short_name', models.CharField(default='Vincent Dania', max_length=80)),
                ('site_description', models.TextField(default='Senior programme and project leader, IT professional, and digital builder working at the intersection of social impact, governance, and technology.')),
                ('site_keywords', models.CharField(default='Vincent Dania, programme manager, project manager, IT professional, digital transformation, social impact', max_length=255)),
                ('location', models.CharField(default='Abuja, Nigeria', max_length=120)),
                ('public_email', models.EmailField(default='vincentdania@live.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='+2348034210082', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-]{10,20}$')])),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/vincentdania/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('contact_intro', models.TextField(default='For senior programme leadership, technology-enabled delivery, consulting, or advisory opportunities, get in touch.')),
                ('footer_note', models.CharField(default='African-rooted, globally relevant leadership across programmes, policy, and technology.', max_length=160)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible_in_footer', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
