# Generated by Django 5.2.12 on 2026-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_badge_label', models.CharField(default='Blog', max_length=80)),
                ('index_title', models.CharField(default='Writing on institutions, delivery, policy, and digital systems.', max_length=255)),
                ('index_intro', models.TextField(default='A curated archive of essays, practical reflections, and research-led thinking grounded in programme implementation, public value, and technology-enabled systems change.')),
                ('featured_badge_label', models.CharField(default='Featured post', max_length=80)),
                ('featured_fallback_title', models.CharField(default='Practical thinking for systems that serve people well.', max_length=255)),
                ('archive_eyebrow', models.CharField(default='Archive', max_length=80)),
                ('archive_title', models.CharField(default='Explore perspectives on governance, institutional effectiveness, social protection, and digital execution.', max_length=255)),
                ('archive_intro', models.TextField(default='Search by topic, filter the archive, and move from strategic reflections to implementation lessons with a more editorial reading experience.')),
                ('archive_link_label', models.CharField(default='Full archive', max_length=80)),
                ('subscribe_badge_label', models.CharField(default='Subscribe', max_length=80)),
                ('subscribe_title', models.CharField(default='Receive new essays directly.', max_length=255)),
                ('subscribe_description', models.TextField(default='Join the list for practical reflections on programme leadership, policy, institutional performance, and digital systems that create measurable value.')),
                ('detail_back_label', models.CharField(default='Back to blog', max_length=80)),
                ('detail_meta_heading', models.CharField(default='Post details', max_length=120)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Blog settings',
                'verbose_name_plural': 'Blog settings',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Navigation item',
                'verbose_name_plural': 'Navigation items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_cv_button_label',
            field=models.CharField(default='Download Full CV', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_button_label',
            field=models.CharField(default='Send Email', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapp_button_label',
            field=models.CharField(default='Chat on WhatsApp', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='Designed & developed by Vincent Dania. All rights reserved.', help_text='The current year is prepended automatically on the site footer.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_cta_label',
            field=models.CharField(default='Work with Vincent', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_cta_link',
            field=models.CharField(default='#contact', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_label',
            field=models.CharField(default='View Portfolio', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_cta_link',
            field=models.CharField(default='#tech', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_contact_label',
            field=models.CharField(default='Contact Me', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_contact_link',
            field=models.CharField(default='/#contact', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_cv_label',
            field=models.CharField(default='Download CV', max_length=80),
        ),
    ]
